# version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /workspace
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # command: sleep infinity
  db:
    image: postgres
    # restart: always
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 134217728
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    depends_on:
      - backend
    # volumes:
    #   - ./tests/api:/workspace/tests

# volumes: