[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "macros", "chrono", "uuid" ] }
dotenvy = "0.15"
validator = { version = "0.20", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.6", features = ["trace", "cors"] }
jsonwebtoken = "9"
argon2 = "0.5"
hashed_password = "1"
utoipa = { version = "5", features = ["uuid", "chrono", "axum_extras"]}
utoipa-swagger-ui = { version = "9", features = ["axum"] }